### ISSUE TITLE
Unable to compile custom xml with companion Nodeset

### ISSUE THREAD

**Issue by farhan296** [OPCFoundation/UA-ModelCompiler#128]
Hello,
I am trying to compile my project. I have an app.xml Model design which depends on Opc.Ua.Safety Nodset2. I am compiling using the following command and get the error below. I have also tried using absolute paths and also I have verified that MyTestObj is not used anywhere within my project.

------------------------------------------------------------------------------------

Opc.Ua.ModelCompiler.exe compile -d2 .\app.xml -d2 .\Opc.Ua.Safety.NodeSet2.xml,Opc.Ua.Safety,Safety -cg .\app.csv -version v105 -exclude Draft -o2 ".\generated"
[InvalidOperationException] The SymbolicId is already used by another node: MyTestObj.

========================
at ModelCompiler.ModelCompilerValidator.UpdateNamesAndIdentifiers(NodeDesign node, NodeDesign parent) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 2570
at ModelCompiler.ModelCompilerValidator.Import(ModelDesign model, NodeDesign node, NodeDesign parent) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 2390
at ModelCompiler.ModelCompilerValidator.LoadModelDesign(String designFilePath, String identifierFilePath, Boolean generateIds) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 208
at ModelCompiler.ModelCompilerValidator.LoadDesignFile(List`1 namespaces, String designFilePath, String identifierFilePath, Boolean generateIds) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 1001
at ModelCompiler.ModelCompilerValidator.ValidateModel(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 1326
at ModelCompiler.ModelCompilerValidator.Validate(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 1024
at ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IList`1 designFilePaths, String identifierFilePath, UInt32 startId, String specificationVersion, Boolean useAllowSubtypes, IList`1 exclusions, String modelVersion, String modelPublicationDate, Boolean releaseCandidate, Boolean extractIdentifiers) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelGenerator2.cs:line 125
at ModelCompiler.ModelCompilerApplication.<>c__DisplayClass13_0.b__0() in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelCompilerApplication.cs:line 480
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.b__0(CancellationToken _)
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
at ModelCompiler.ModelCompilerApplication.Run(String[] args) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelCompilerApplication.cs:line 31
at Program.

$(String[] args) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\Program.cs:line 27

---------------------------------------------------------------------------------
 

And the app.xml is as follows:

```
<?xml version="1.0" encoding="utf-8"?>

<ModelDesign
  xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ua="http://opcfoundation.org/UA/"
  xmlns:Safety="http://opcfoundation.org/UA/Safety"
  xmlns:app="urn:open62541.server.application"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  TargetNamespace="urn:open62541.server.application"
  TargetVersion="0.1.0"
  TargetPublicationDate="2022-05-02T00:00:00Z"
  xmlns="http://opcfoundation.org/UA/ModelDesign.xsd">

  <Namespaces>
    <Namespace Name="opc" Prefix="opc" Version="1.03" PublicationDate="2013-12-02T00:00:00Z">http://opcfoundation.org/UA</Namespace>
    <Namespace Name="Safety" Prefix="Safety" PublicationDate="2022-06-28T00:00:00Z" Version="1.05.02" FilePath="./Opc.Ua.Safety.NodeSet2">http://opcfoundation.org/UA/Safety</Namespace>
    <Namespace Name="app" Prefix="app">urn:open62541.server.application</Namespace>
  </Namespaces>

  <Object SymbolicName="app:MyTestObj " TypeDefinition="Safety:SafetyProviderType">
    <References>
      <Reference IsInverse="true">
        <ReferenceType>ua:Organizes</ReferenceType>
        <TargetId>Safety:SafetyACSet</TargetId>
      </Reference>
    </References>
  </Object> 
  
</ModelDesign>

```

---------------------------------------------------------------------------------

I have debugged the issue and found out that the compiler tries to add MyTestObj twice one at [line 1316](https://github.com/OPCFoundation/UA-ModelCompiler/blob/c7a9be18743761ca79a7b68f94486a5f475ddc5e/Opc.Ua.ModelCompiler/ModelDesignerValidator.cs#L1316) and the second one at [line 1326](https://github.com/OPCFoundation/UA-ModelCompiler/blob/c7a9be18743761ca79a7b68f94486a5f475ddc5e/Opc.Ua.ModelCompiler/ModelDesignerValidator.cs#L1326) causing the above error. Is this the correct workflow or am I missing something?

**Comment by opcfoundation-org** [comment]
Can you try putting the app first in the Namespace list?

**Comment by farhan296** [comment]
Hello,
Thank you putting the app first fixed the issue. Is this a general rule to put the target (first -d2 argument in compile command ) namespace as the first?

**Comment by opcfoundation-org** [comment]
yes on both.
