### ISSUE TITLE
Missing _BinarySchema and/or TypeDictionary_BinarySchema in Opc.Ua.Safety.NodeSet2.xml

### ISSUE THREAD

**Issue by farhan296** [OPCFoundation/UA-ModelCompiler#130]
I am working on a project that uses Open62541 SDK. My application makes use of [Safety Nodesets](https://github.com/OPCFoundation/UA-Nodeset/tree/d9f49576eedb95f4ffaa731bad09779947b287f5/Safety). When I try to generate source code using [Open62541 Nodeset Compiler](https://github.com/open62541/open62541/tree/master/tools/nodeset_compiler) I get the following error

```bash
5>Traceback (most recent call last):
5>  File ".\..\..\..\SDK_Open62541\open62541\tools\generate_datatypes.py", line 95, in <module>
5>    parser.create_types()
5>  File ".\..\..\..\SDK_Open62541\open62541\tools\nodeset_compiler\type_parser.py", line 377, in create_types
5>    self.parse_types()
5>  File ".\..\..\..\SDK_Open62541\open62541\tools\nodeset_compiler\type_parser.py", line 419, in parse_types
5>    self.parseTypeDefinitions(self.outname, f)
5>  File ".\..\..\..\SDK_Open62541\open62541\tools\nodeset_compiler\type_parser.py", line 321, in parseTypeDefinitions
5>    raise RuntimeError("Infinite loop detected or type not found while processing types " +
5>RuntimeError: Infinite loop detected or type not found while processing types MyResponseSPDUDataType: unknonwn subtype ['Safety:OutFlagsType']. If the unknown subtype is 'Bit', then maybe a struct with optional fields is defined wrong in the .bsd-file. If not, maybe you need to import additional types with the --import flag. E.g. '--import=UA_TYPES#/path/to/deps/ua-nodeset/Schema/Opc.Ua.Types.bsd'
```

While debugging I noticed that the Open62541 nodeset compiler is not including the UAModel.Safety.Types.bsd file generated by the UA-Model Compiler and the reason is that the [Opc.Ua.Safety.NodeIds.csv](https://github.com/OPCFoundation/UA-Nodeset/blob/d9f49576eedb95f4ffaa731bad09779947b287f5/Safety/Opc.Ua.Safety.NodeIds.csv) and [Opc.Ua.Safety.NodeSet2.xml](https://github.com/OPCFoundation/UA-Nodeset/blob/d9f49576eedb95f4ffaa731bad09779947b287f5/Safety/Opc.Ua.Safety.NodeSet2.xml) is missing "_BinarySchema" and/or "TypeDictionary_BinarySchema" nodes which is required by the Open62541 nodeset compiler (see [nodeset.py#L431](https://github.com/open62541/open62541/blob/0b1d72f157c6a8f0c05aca56896b217c816e9827/tools/nodeset_compiler/nodeset.py#L431)). Is there any workaround for this? Also see the [Issue here](https://github.com/open62541/open62541/issues/5815).

I compile the [Safety Nodesets](https://github.com/OPCFoundation/UA-Nodeset/tree/d9f49576eedb95f4ffaa731bad09779947b287f5/Safety) in the following way

```bash
Opc.Ua.ModelCompiler.exe compile-nodesets -input .\OPC_Foundation_Safety-files -o2 .\generated_safety -uri http://opcfoundation.org/UA/Safety

copy .\generated_safety .\generated

```
I compile my App.xml model design file as follows
```bash
del .\AppModel.csv

Opc.Ua.ModelCompiler.exe compile -d2 .\AppModel.xml -d2 .\OPC_Foundation_Safety-files\Opc.Ua.Safety.NodeSet2.xml,Safety,Safety -cg .\AppModel.csv -version v105 -o2 .\generated
```
My App.xml model design is as follows
```xml
<?xml version="1.0" encoding="utf-8"?>

<ModelDesign
  xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ua="http://opcfoundation.org/UA/"
  xmlns:Safety="http://opcfoundation.org/UA/Safety"
  xmlns:app="urn:open62541.server.application"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  TargetNamespace="urn:open62541.server.application"
  TargetVersion="0.1.0"
  TargetPublicationDate="2022-05-02T00:00:00Z"
  xmlns="http://opcfoundation.org/UA/ModelDesign.xsd">

  <Namespaces>
    <Namespace Name="app" Prefix="app">urn:open62541.server.application</Namespace>
    <Namespace Name="Safety" Prefix="Safety" PublicationDate="2022-06-28T00:00:00Z" Version="1.05.02">http://opcfoundation.org/UA/Safety</Namespace>
    <Namespace Name="ua" Prefix="ua" Version="1.05.02" PublicationDate="2022-11-01T00:00:00Z">http://opcfoundation.org/UA/</Namespace>
  </Namespaces>

  <DataType SymbolicName="app:MyResponseSPDUDataType" BaseType="Safety:ResponseSPDUDataType" IsAbstract="false">
    <Fields>      
      <Field Name="MyOutSafetyData"  DataType="app:MySafetyData1Type"></Field>
      <Field Name="MyOutNonSafetyData" DataType="app:MyNonSafetyData1Type"></Field>
    </Fields>
  </DataType>

  <DataType SymbolicName="app:MySafetyData1Type" BaseType="ua:Structure" >   
    <Fields>
      <Field Name="Field_1" DataType="ua:UInt32"></Field>
      <Field Name="Field_2" DataType="ua:UInt32"></Field>
      <Field Name="Field_4" DataType="ua:Boolean"></Field>     
    </Fields>
  </DataType>

  <DataType SymbolicName="app:MyNonSafetyData1Type" BaseType="ua:Structure">
    <Fields>
      <Field Name="Item1" DataType="ua:UInt32"></Field>
    </Fields>
  </DataType>


  <!-- ### Object ###-->

  <Object SymbolicName="app:MySafetyProvider" TypeDefinition="Safety:SafetyProviderType">
    <Children>
      <Method SymbolicName="app:MyReadSafetyData">
        <InputArguments>
          <Argument Name="InSafetyConsumerID" DataType="ua:UInt32" ValueRank="Scalar"></Argument>
          <Argument Name="InMonitoringNumber" DataType="ua:UInt32" ValueRank="Scalar"></Argument>
          <Argument Name="InFlags" DataType="Safety:InFlagsType" ValueRank="Scalar"></Argument>
        </InputArguments>
        <OutputArguments>
          <Argument Name="OutSafetyData" DataType="app:MySafetyData1Type" ></Argument>
          <Argument Name="OutFlags" DataType="Safety:OutFlagsType" ValueRank="Scalar"></Argument>
          <Argument Name="OutSPDU_ID_1" DataType="ua:UInt32" ValueRank="Scalar"></Argument>
          <Argument Name="OutSPDU_ID_2" DataType="ua:UInt32" ValueRank="Scalar"></Argument>
          <Argument Name="OutSPDU_ID_3" DataType="ua:UInt32" ValueRank="Scalar"></Argument>
          <Argument Name="OutSafetyConsumerID" DataType="ua:UInt32" ValueRank="Scalar"></Argument>
          <Argument Name="OutMonitoringNumber" DataType="ua:UInt32" ValueRank="Scalar"></Argument>
          <Argument Name="OutCRC" DataType="ua:UInt32" ValueRank="Scalar"></Argument>
          <Argument Name="OutNonSafetyData" DataType="app:MyNonSafetyData1Type" ></Argument>
        </OutputArguments>
      </Method>           
      <Object SymbolicName="app:MySafetyPDUs" TypeDefinition="Safety:SafetyPDUsType">
        <Children>
          <Variable SymbolicName="app:MyRequestSPDU" DataType="Safety:RequestSPDUDataType" TypeDefinition="ua:BaseDataVariableType"></Variable>
          <Variable SymbolicName="app:MyResponseSPDU" DataType="app:MyResponseSPDUDataType" TypeDefinition="ua:BaseDataVariableType"></Variable>
        </Children>
      </Object>
    </Children>

    <References>
      <Reference IsInverse="true">
        <ReferenceType>ua:Organizes</ReferenceType>
        <TargetId>Safety:SafetyACSet</TargetId>
      </Reference>
    </References>
  </Object>   
  
</ModelDesign>
```

**Comment by opcfoundation-org** [comment]
The DataTypeDictionaries have been removed from 1.05 (feature replaced by the DataTypeDefinition Attribute).
New nodesets are permitted to omit them. 
You will need to update your generator to handle this case.

**Comment by farhan296** [comment]
Thank you for the response. I shall create mantis issue as suggested.
Further, Is there any example for the usage of DataTypeDefinition Attribute? Do I have to include a DataTypeDefinition block in my ModelDesign file (App.xml) or will the UA-Model compiler generate accordingly?

**Comment by opcfoundation-org** [comment]
ModelCompiler generates the DataTypeDefinition in the NodeSet.
