### ISSUE TITLE
Template 'ModelCompiler.Templates.XmlSchema.Union.xml' not found.

### ISSUE THREAD

**Issue by joematoe** [OPCFoundation/UA-ModelCompiler#137]
I am following the steps in the Example Generation.  When I run BuildStandardTypes.bat, I get the following error:

```
[ApplicationException] Template 'ModelCompiler.Templates.XmlSchema.Union.xml' not found.
 [ArgumentNullException] Value cannot be null. (Parameter 'stream')

   at CodeGenerator.Template..ctor(TextWriter writer, Boolean written, String templatePath, Assembly assembly) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\StackGenerator\Shared\Template.cs:line 77
   at CodeGenerator.Template.WriteTemplate(Object container, String token, String prefix) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\StackGenerator\Shared\Template.cs:line 546
   at CodeGenerator.Template.WriteTemplate(Context context) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\StackGenerator\Shared\Template.cs:line 295
   at ModelCompiler.ModelGenerator2.WriteTemplate_XmlSchema(String filePath, List`1 nodes) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelGenerator2.cs:line 921
   at ModelCompiler.ModelCompilerApplication.<>c__DisplayClass13_0.<Compile>b__0() in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelCompilerApplication.cs:line 526
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at ModelCompiler.ModelCompilerApplication.Run(String[] args) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelCompilerApplication.cs:line 31
   at Program.<Main>$(String[] args) in C:\UA-ModelCompiler\Opc.Ua.ModelCompiler\Program.cs:line 27

Failed DemoModel
```

After the DemoModel fails, there are a bunch of subsequent errors - e.g., no stack is generated, moving of files fails because folders haven't been created, etc.  

I have verified that Union.xml is in the path specified, but it looks like the skeleton for a template.  

Any ideas?

**Comment by opcfoundation-org** [comment]
Fixed
