### ISSUE TITLE
Parse error in the loaded model xml file.

### ISSUE THREAD

**Issue by Graos** [OPCFoundation/UA-ModelCompiler#57]
I get the following error  when the attached xml file is loaded.
Error parsing file D:\ModelCompiler\ReducedCI874TypesTest.xml
at Opc.Ua.ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in D:\UA-ModelCompiler-master\ModelCompiler\ModelDesignerValidator.cs:line 1001 at Opc.Ua.ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IList`1 designFilePaths, String identifierFilePath, UInt32 startId, String specificationVersion) in D:\UA-ModelCompiler-master\ModelCompiler\ModelGenerator2.cs:line 96 at Opc.Ua.ModelCompiler.Program.ProcessCommandLine2(List`1 tokens) in D:\UA-ModelCompiler-master\ModelCompiler\Program.cs:line 424
There is an error in XML document (2, 2).
at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Opc.Ua.Schema.SchemaValidator.LoadFile(Type type, String path) in D:\UA-ModelCompiler-master\Core\Types\Schemas\SchemaValidator.cs:line 254 at Opc.Ua.ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in D:\UA-ModelCompiler-master\ModelCompiler\ModelDesignerValidator.cs:line 991

There is an error in XML document (2, 2).
at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Opc.Ua.Schema.SchemaValidator.LoadFile(Type type, Stream stream) in D:\UA-ModelCompiler-master\Core\Types\Schemas\SchemaValidator.cs:line 272 at Opc.Ua.CodeGenerator.TypeDictionaryValidator.Validate(Stream stream) in D:\UA-ModelCompiler-master\ModelCompiler\StackGenerator\Validators\TypeDictionaryValidator.cs:line 147 at Opc.Ua.ModelCompiler.ModelCompilerValidator.ImportTypeDictionary(Stream stream, String resourcePath) in D:\UA-ModelCompiler-master\ModelCompiler\ModelDesignerValidator.cs:line 632 at Opc.Ua.ModelCompiler.ModelCompilerValidator.ImportTypeDictionary(String filePath, String resourcePath) in D:\UA-ModelCompiler-master\ModelCompiler\ModelDesignerValidator.cs:line 624 at Opc.Ua.ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in D:\UA-ModelCompiler-master\ModelCompiler\ModelDesignerValidator.cs:line 997

[ReducedCI874TypesTest.zip](https://github.com/OPCFoundation/UA-ModelCompiler/files/5113933/ReducedCI874TypesTest.zip)

**Comment by blair-long** [comment]
Looks like you are using the UANodeSet.xml as INPUT for ModelCompiler. Actually, UANodeSet.xml is ModelCompiler's OUTPUT, and ModelDesign.xml is the INPUT.
